name: 'Terraform - State'

on:
  pull_request:
    branches: [dev]

jobs:
  terraform-state:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Running Terraform State Jobs"
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Set Environment Variables
      run: |
        echo "STORAGE_ACCOUNT_NAME=$(terraform output storage_account_name)" >> $GITHUB_ENV
      working-directory: ./terraform-state

    - name: Check if Storage Account Exists
      id: check_storage_account
      run: |
        if $(az storage account check-name --name ${{ env.STORAGE_ACCOUNT_NAME }} --query nameAvailable); then
          echo "::set-output name=exists::false"
        else
          echo "::set-output name=exists::true"
        fi

    - name: Terraform Init
      if: steps.check_storage_account.outputs.exists == 'false'
      run: terraform init
      working-directory: ./terraform-state

    - name: Terraform Plan
      if: steps.check_storage_account.outputs.exists == 'false'
      run: terraform plan -var-file="terraform.tfvars"
      working-directory: ./terraform-state

    - name: Terraform Apply
      if: steps.check_storage_account.outputs.exists == 'false'
      run: terraform apply -auto-approve -var-file="terraform.tfvars"
      working-directory: ./terraform-state