name: 'Terraform - State'

on:
  pull_request:
    branches: [dev]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Check if Storage Account Exists
      id: check_storage_account
      run: |
        if $(az storage account check-name --name terrdb7473 --query nameAvailable); then
          echo "::set-output name=exists::false"
          echo "Storage Account does not exist"
        else
          echo "::set-output name=exists::true"
          echo "Storage Account exists"
        fi

    - name: Terraform Init
      if: steps.check_storage_account.outputs.exists == 'false'
      run: terraform init
      working-directory: ./terraform-state

    - name: Terraform Plan
      if: steps.check_storage_account.outputs.exists == 'false'
      run: terraform plan
      working-directory: ./terraform-state

    - name: Terraform Apply
      if: steps.check_storage_account.outputs.exists == 'false'
      run: terraform apply -auto-approve
      working-directory: ./terraform-state        