name: 'Terraform - State'

on:
  pull_request:
    branches: [dev]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Environment Variables
      run: |
        echo "STORAGE_ACCOUNT_NAME=$(terraform output storage_account_name)" >> $GITHUB_ENV
      working-directory: ./terraform-state

    - name: Check if Storage Account Exists
      id: check_storage_account
      run: |
        if $(az storage account check-name --name "$STORAGE_ACCOUNT_NAME" --query nameAvailable); then
          echo "::set-output name=exists::false"
          echo "Storage Account does not exist"
        else
          echo "::set-output name=exists::true"
          echo "Storage Account exists"
        fi

